# Generated by Django 3.2.4 on 2021-06-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='http://www.amityinternational.com/wp-content/uploads/2019/02/product-placeholder.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
